# Generated by Django 6.0.4 on 2026-05-15 15:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AirplaneProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL изображения')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='URL видео')),
                ('status', models.CharField(choices=[('active', 'Действует'), ('deleted', 'Удалена')], default='active', max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Вес (кг)')),
                ('material', models.CharField(default='Алюминий', max_length=100, verbose_name='Материал')),
                ('manufacturer', models.CharField(default='АвиаЗавод', max_length=200, verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Авиапродукт',
                'verbose_name_plural': 'Авиапродукты',
                'db_table': 'airplane_products',
            },
        ),
        migrations.CreateModel(
            name='AirplaneRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('deleted', 'Удалён'), ('formed', 'Сформирован'), ('completed', 'Завершён'), ('rejected', 'Отклонён')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('formed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('client_name', models.CharField(default='Гость', max_length=200, verbose_name='Для кого')),
                ('purpose', models.CharField(blank=True, max_length=200, verbose_name='Цель использования')),
                ('aircraft_model', models.CharField(blank=True, max_length=100, verbose_name='Модель самолёта')),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='requests', to=settings.AUTH_USER_MODEL)),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='moderated_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'db_table': 'airplane_requests',
            },
        ),
        migrations.CreateModel(
            name='AirplaneRequestItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='request_items', to='bmstu_lab.airplaneproduct')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='items', to='bmstu_lab.airplanerequest')),
            ],
            options={
                'verbose_name': 'Позиция заявки',
                'verbose_name_plural': 'Позиции заявок',
                'db_table': 'airplane_request_items',
                'unique_together': {('request', 'product')},
            },
        ),
    ]
