# Generated by Django 6.0.4 on 2026-05-30 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Airplane',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200, verbose_name='Модель самолёта')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL изображения')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='URL видео')),
                ('status', models.CharField(choices=[('active', 'Действует'), ('deleted', 'Удалён')], default='active', max_length=20)),
                ('weight', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Вес (кг)')),
                ('max_speed', models.IntegerField(blank=True, null=True, verbose_name='Макс. скорость (км/ч)')),
                ('range_km', models.IntegerField(blank=True, null=True, verbose_name='Дальность полёта (км)')),
                ('manufacturer', models.CharField(default='Боинг', max_length=200, verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'Самолёт',
                'verbose_name_plural': 'Самолёты',
                'db_table': 'airplanes',
            },
        ),
        migrations.CreateModel(
            name='AirplaneConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order_index', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('result_field', models.CharField(blank=True, max_length=255, null=True, verbose_name='Вычисляемое поле')),
                ('airplane', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='config_items', to='bmstu_lab.airplane')),
            ],
            options={
                'verbose_name': 'Самолёт в конфигурации',
                'verbose_name_plural': 'Самолёты в конфигурациях',
                'db_table': 'airplane_configurations',
            },
        ),
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('deleted', 'Удалён'), ('formed', 'Сформирован'), ('completed', 'Завершён'), ('rejected', 'Отклонён')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('formed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('customer_name', models.CharField(default='Гость', max_length=200)),
                ('purpose', models.CharField(blank=True, max_length=200, verbose_name='Назначение')),
                ('aircraft_model', models.CharField(blank=True, max_length=100, verbose_name='Модель ВС')),
                ('mm_field', models.CharField(blank=True, max_length=200, verbose_name='М-М поле (особые требования)')),
                ('delivery_cost', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('airplanes', models.ManyToManyField(through='bmstu_lab.AirplaneConfiguration', to='bmstu_lab.airplane')),
                ('creator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='configurations', to=settings.AUTH_USER_MODEL)),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='moderated_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Конфигурация',
                'verbose_name_plural': 'Конфигурации',
                'db_table': 'configurations',
            },
        ),
        migrations.AddField(
            model_name='airplaneconfiguration',
            name='configuration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='items', to='bmstu_lab.configuration'),
        ),
        migrations.AlterUniqueTogether(
            name='airplaneconfiguration',
            unique_together={('configuration', 'airplane')},
        ),
    ]
