# Generated by Django 6.0.4 on 2026-05-30 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='airplane',
            name='depth',
            field=models.IntegerField(blank=True, null=True, verbose_name='Глубина (мм)'),
        ),
        migrations.AddField(
            model_name='airplane',
            name='height',
            field=models.IntegerField(blank=True, null=True, verbose_name='Высота (мм)'),
        ),
        migrations.AddField(
            model_name='airplane',
            name='material',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Материал'),
        ),
        migrations.AddField(
            model_name='airplane',
            name='width',
            field=models.IntegerField(blank=True, null=True, verbose_name='Ширина (мм)'),
        ),
    ]
