# Generated by Django 6.0.4 on 2026-05-23 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='airplanerequest',
            name='total_cost',
        ),
        migrations.AddField(
            model_name='airplanerequest',
            name='delivery_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='airplanerequest',
            name='special_request',
            field=models.CharField(blank=True, max_length=200, verbose_name='Особое пожелание'),
        ),
        migrations.AddField(
            model_name='airplanerequestitem',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='airplanerequestitem',
            name='result_field',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='airplanerequest',
            name='aircraft_model',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='airplanerequest',
            name='client_name',
            field=models.CharField(default='Гость', max_length=200),
        ),
        migrations.AlterField(
            model_name='airplanerequest',
            name='purpose',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='airplanerequestitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
