# Generated by Django 6.0.4 on 2026-05-10 18:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0004_order_session_key'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заявка', 'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelOptions(
            name='orderservice',
            options={'verbose_name': 'Услуга в заявке', 'verbose_name_plural': 'Услуги в заявках'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Услуга', 'verbose_name_plural': 'Услуги'},
        ),
        migrations.RemoveField(
            model_name='order',
            name='session_key',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='service',
            name='depth',
        ),
        migrations.RemoveField(
            model_name='service',
            name='height',
        ),
        migrations.RemoveField(
            model_name='service',
            name='width',
        ),
        migrations.AddField(
            model_name='order',
            name='client_name',
            field=models.CharField(default='Не указано', max_length=200, verbose_name='Для кого (организация/ФИО)'),
        ),
        migrations.AddField(
            model_name='order',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='moderator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='moderated_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='purpose',
            field=models.CharField(blank=True, max_length=200, verbose_name='Цель использования'),
        ),
        migrations.AddField(
            model_name='service',
            name='manufacturer',
            field=models.CharField(default='АвиаЗавод', max_length=200, verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='service',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Вес (кг)'),
        ),
        migrations.AlterField(
            model_name='orderservice',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='order_services', to='bmstu_lab.order'),
        ),
        migrations.AlterField(
            model_name='orderservice',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='orderservice',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='order_services', to='bmstu_lab.service'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='service',
            name='image_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL изображения'),
        ),
        migrations.AlterField(
            model_name='service',
            name='material',
            field=models.CharField(default='Алюминий', max_length=100, verbose_name='Материал'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Стоимость'),
        ),
        migrations.AlterField(
            model_name='service',
            name='video_url',
            field=models.URLField(blank=True, null=True, verbose_name='URL видео'),
        ),
        migrations.AlterModelTable(
            name='orderservice',
            table='order_services',
        ),
    ]
