# Generated by Django 6.0.4 on 2026-05-11 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0005_alter_order_options_alter_orderservice_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='order',
            name='moderator',
        ),
        migrations.AlterField(
            model_name='order',
            name='client_name',
            field=models.CharField(default='Гость', max_length=200, verbose_name='Для кого (организация/ФИО)'),
        ),
    ]
