# Generated by Django 4.2.4 on 2026-04-17 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('deleted', 'Удалён'), ('formed', 'Сформирован'), ('completed', 'Завершён'), ('rejected', 'Отклонён')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('formed_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='orders', to=settings.AUTH_USER_MODEL)),
                ('moderator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='moderated_orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL изображения')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='URL видео')),
                ('status', models.CharField(choices=[('active', 'Действует'), ('deleted', 'Удалена')], default='active', max_length=20)),
                ('width', models.CharField(blank=True, max_length=50, verbose_name='Ширина')),
                ('height', models.CharField(blank=True, max_length=50, verbose_name='Высота')),
                ('depth', models.CharField(blank=True, max_length=50, verbose_name='Глубина')),
                ('material', models.CharField(blank=True, max_length=100, verbose_name='Материал')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
                'db_table': 'services',
            },
        ),
        migrations.CreateModel(
            name='OrderService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bmstu_lab.order')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='bmstu_lab.service')),
            ],
            options={
                'verbose_name': 'Услуга в заявке',
                'verbose_name_plural': 'Услуги в заявках',
                'db_table': 'order_service',
                'unique_together': {('order', 'service')},
            },
        ),
    ]
