# Generated by Django 6.0.4 on 2026-04-19 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='organization',
        ),
    ]
