# Generated by Django 6.0.4 on 2026-04-19 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0002_remove_order_organization'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='order',
            name='unique_draft_per_user',
        ),
        migrations.RemoveField(
            model_name='order',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='order',
            name='moderator',
        ),
    ]
