version: '3.8'

services:
  db:
    image: postgres:15
    container_name: postgres
    ports:
      - "5455:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: airplane_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    container_name: minio_server
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"

  web:
    build: .
    container_name: django_app
    ports:
      - "8000:8000"
    environment:
      DEBUG: 1
      DJANGO_SETTINGS_MODULE: airplane_construction_project.settings
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin123
      MINIO_USE_HTTPS: "False"
    depends_on:
      - db
      - minio
    volumes:
      - .:/app

volumes:
  postgres_data: